"""Renders the gateway's Caddyfile.

Caddy does the HTTP work — parsing, framing, timeouts, streaming — because that
is where a hand-rolled proxy loses. This module decides only what is exposed and
on what terms: admission is delegated to the authcheck service via forward_auth,
so no credential and no digest ever appears in the generated file.

Two header forms are accepted because the SDKs differ: OpenAI clients send
`Authorization: Bearer <token>`, Anthropic clients send `x-api-key: <token>`.
Per Caddy's matcher docs, different header fields inside one matcher set are
AND-ed, so the two forms cannot be expressed as a plain header matcher — a CEL
expression with `||` is the construct that gives OR across fields.
"""

from __future__ import annotations

# Never reachable through the gateway: operational surface with no auth of its
# own. /v1/stats/reset is an unauthenticated POST that wipes metrics.
BLOCKED_PATHS = ("/v1/stats*", "/metrics", "/v1/routing/*")

UNAUTHORIZED_BODY = (
    '{"error":{"message":"Missing or invalid API key. Send it as '
    "'Authorization: Bearer <token>' or 'x-api-key: <token>'.\","
    '"type":"authentication_error","code":401}}'
)


DEFAULTS = {
    "max_body": "32MB",            # matches Switchyard's own 32 MiB limit
    "read_timeout": "900s",        # long completions must not be cut off
    "access_log": "/var/log/switchyard/gateway.log",
    "roll_size": "100MiB",         # Caddy rolls this itself
    "roll_keep": 3,
    "roll_keep_days": 30,
    "routing_log_max_gib": 1.0,    # used by the accounting ingest, not by Caddy
    # Only the operator knows this: the address clients actually reach, in front
    # of whatever reverse proxy terminates TLS. Display only; Caddy ignores it.
    "public_url": "",
}


def render(upstream: str = "switchingyard:4000", authcheck: str = "authcheck:9000",
           listen: str = ":4000", max_body: str | None = None,
           read_timeout: str | None = None, access_log: str | None = None,
           roll_size: str | None = None, roll_keep: int | None = None,
           roll_keep_days: int | None = None, **_ignored) -> str:
    """Build the Caddyfile.

    Admission is delegated to `authcheck` via forward_auth, which sends a GET
    with the original headers and no body. On 200 the request proceeds and the
    caller's own credential travels on to the provider untouched — that relay is
    the whole point, so nothing here may strip Authorization.
    """
    max_body = max_body or DEFAULTS["max_body"]
    read_timeout = read_timeout or DEFAULTS["read_timeout"]
    access_log = access_log or DEFAULTS["access_log"]
    roll_size = roll_size or DEFAULTS["roll_size"]
    roll_keep = DEFAULTS["roll_keep"] if roll_keep is None else roll_keep
    roll_keep_days = DEFAULTS["roll_keep_days"] if roll_keep_days is None else roll_keep_days
    blocked = "\n".join(
        f"\thandle {path} {{\n\t\trespond 404\n\t}}\n" for path in BLOCKED_PATHS)

    authed = f"""\thandle {{
\t\t# Membership check only: authcheck holds SHA-256 digests, never keys.
\t\t# It answers 200 + X-Switchyard-Client, or 401. Any non-2xx denies, so a
\t\t# checker that is down fails closed rather than open.
\t\tforward_auth {authcheck} {{
\t\t\turi /auth
\t\t\t# the tag lands in Switchyard's routing log as trial_id, which is what
\t\t\t# gives accounting a per-user breakdown
\t\t\tcopy_headers X-Switchyard-Client>X-Switchyard-Trial-Id
\t\t}}

\t\treverse_proxy {upstream} {{
\t\t\t# Authorization is deliberately NOT stripped: the caller's own key is
\t\t\t# what pays for the request upstream.
\t\t\t# -1 disables response buffering so streamed tokens arrive as sent
\t\t\tflush_interval -1
\t\t\ttransport http {{
\t\t\t\tread_timeout {read_timeout}
\t\t\t}}
\t\t}}
\t}}

"""

    return f"""# Generated by the Switchyard management TUI. Do not edit by hand —
# it is rewritten whenever settings change. Restart the gateway to apply:
#     docker compose restart gateway
#
# Admission is delegated to authcheck; callers present their own provider key.

{{
\t# no admin API: nothing needs it, and it is remote-control surface
\tadmin off
\tauto_https off
}}

{listen} {{
\t# Caddy rolls this file itself — size, count and age below. Container stdout
\t# is capped separately by the compose logging driver.
\tlog {{
\t\toutput file {access_log} {{
\t\t\troll_size {roll_size}
\t\t\troll_keep {roll_keep}
\t\t\troll_keep_for {roll_keep_days * 24}h
\t\t}}
\t\t# Caddy redacts Authorization, Cookie, Set-Cookie and Proxy-Authorization by
\t\t# default — but NOT x-api-key, which carries the very same credential for
\t\t# Anthropic-style clients. Verified: it was written to disk in full. Drop it.
\t\tformat filter {{
\t\t\twrap json
\t\t\tfields {{
\t\t\t\trequest>headers>X-Api-Key delete
\t\t\t}}
\t\t}}
\t}}

\trequest_body {{
\t\tmax_size {max_body}
\t}}

\t# answered by the gateway itself; reveals nothing about the router
\thandle /health {{
\t\trespond `{{"status":"ok","service":"switchyard-gateway"}}` 200
\t}}

{blocked}
{authed}}}
"""
